### ISSUE TITLE
Possible misprint on web-site (C++ mention)

### ISSUE THREAD

**Issue by igoose1** [ambientsound/pms#126]
Hello!

Your client is written fully in Go. But if you open the web-site of pms you can
see "written in C++ and ncurses" which looks like an erratum. I couldn't find
site's public repo (but I wasn't searching a lot) and your e-mail so I'm
writing here.

**Comment by ambientsound** [comment]
Hi @igoose1,

Thanks for writing. pms was originally written in C++ and ncurses. It was subsequently re-written in Go. However, the Go version does not contain a 100% complete feature set from the previous version, and thus was never really replaced as the "official" version.

I suppose the text could be updated anyways, since this is the current version, and the only one which will receive updates.

Regards, @ambientsound

**Comment by igoose1** [comment]
Thanks for the answer, @ambientsound.

Close the issue yourself, please. I don't know if you've got any other TODO
lists like opened issues :)
